name: Notify Module Maintainers
on:
  pull_request:
    paths:
      - 'modules/**'

permissions:
  pull-requests: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - name: Run BCR helper
        uses: meteorcloudy/continuous-integration/actions/bcr-helper@48e80e9a1bb997fb45eaac23ddcf4dfd84a090eb # master
        with:
          token: ${{ secrets.TEST_BCR_TOKEN }}
